//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mostafa
    {
        public int Id { get; set; }
        public string Names { get; set; }
        public string Email { get; set; }
        public string Derpratment { get; set; }
        public Nullable<int> Password_ { get; set; }
    }
}
